name: main-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
      - name: Print Go go-version
        run: go version
      - name: Unit test of go
        run: go test -v ./...
        

